site_name: Transfer Learning for 3D Point Cloud Semantic Segmentation
nav:
  - Home: index.md
  - Foundations: tl.md
  - Previous Works: tlintro.md
  - AUDA Framwork: ssintro.md
  - Experiments: experiments.md
  - Implementing Details: implement.md
  - About: about.md
theme: readthedocs

